In [1]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize

def fun(x,a,shp):
    return np.linalg.norm(x-a,2)

shp = (30,30)
x0 = np.zeros(shp[0]*shp[1])
a = np.random.rand(shp[0],shp[1])
a = a.flatten()
res = scipy.optimize.minimize(fun, x0, args=(a,shp),callback=None)
#print (res)
print ((a[:5]))
print ((res['x'][:5]))

x = np.reshape(res['x'],shp)

# x = np.reshape(res,shp)
a = np.reshape(a,shp)
print (round((np.linalg.norm((x - a),'fro'))*100/np.linalg.norm( a),20),"%")


[ 0.7113069   0.27873175  0.36928204  0.43686652  0.41605826]
[ 0.71130694  0.27873178  0.36928206  0.43686654  0.41605828]
3.49551825528e-06 %


# reshape in function (working version aber noch nicht so gut )

In [5]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize

# objective function to minimize:
# Sum (W - Sum a*s)

N = 8
M = 4

m = 2
n = 2

#generate random sequence of filters
W = []
for i in range(N):
    W.append(np.random.rand(m,n))

#definition of the objective function
def fun(params,W,m,n,M,N):
    #recovering the original structure of parameters
    a = params[:N*M]
    X = params[N*M:]
    a = np.reshape(np.array(a),(N,M))
    X = np.reshape(np.array(X),(M,m,n))
    res = 0
    
    for i in range(N):
        # calculating the linear combination of matrices
        a_X = 0
        
        for j in range(M):
            a_X += a[i,j]*X[j,:,:]
            
        # calculating sum of
        res += np.linalg.norm(W[i] - a_X,2)
    return res

shp = (m,n)
params = []

#initializing coefficients for linear combination
params = np.random.rand(N*M+M*n*m)  # N*M for lc coefiicients and m*n*M for matrix weights

res = scipy.optimize.minimize(fun, params, args=(W,m,n,M,N),callback=None)
vals = res['x']
a = vals[:N*M]
X = vals[N*M:]

a = np.reshape(np.array(a),(N,M))
X = np.reshape(np.array(X),(M,m,n))

print ("weights are:")
print (a)
print ("basis filters are:")
print (W)

#random check
for i in range(N):
    coeff_i = a[i,:]
    A = 0
    for j in range(M):
        A += coeff_i[j]*X[j]
    print ("approximation of matrix", i)
    print (np.round((np.linalg.norm(W[i] - A,2))*100,5), "%")
# print (round((np.linalg.norm((x - a),'nuc'))*100/np.linalg.norm( a),20),"%")

weights are:
[[ 1.6532174  -0.04672794  0.50060449  0.04206583]
 [ 0.16521758  0.6778909   0.49593331  1.07924375]
 [ 0.63215046  0.38199753  0.19054562  0.88638792]
 [ 0.11126308  0.50040069  0.7741062  -0.13421517]
 [ 0.22573474  0.80208051  0.56019543  0.59580264]
 [-0.20587779 -0.20002625  0.98472551  0.68545077]
 [ 1.25764748  0.62787688  0.49260431  0.36445454]
 [-0.12294727  0.66686364  0.51909511 -0.14283054]]
basis filters are:
[array([[ 0.97736375,  0.25942074],
       [ 0.83325069,  0.45751872]]), array([[ 0.74163837,  0.88146571],
       [ 0.27362681,  0.84159856]]), array([[ 0.66242188,  0.64862269],
       [ 0.15801017,  0.75848852]]), array([[ 0.48941514,  0.20732922],
       [ 0.86723599,  0.14919291]]), array([[ 0.63695007,  0.5813478 ],
       [ 0.61736866,  0.65231372]]), array([[ 0.80674458,  0.88109149],
       [ 0.14039767,  0.2553895 ]]), array([[ 0.91348914,  0.42145402],
       [ 0.92904871,  0.74658971]]), array([[ 0.2253541 ,  0.08053486],
       [ 0.72303311

In [3]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize


def fun(x,a,W,shp):
    b = x[:len(x)/2]
    c = x[len(x)/2:]
    b = np.reshape(b,shp)
    c = np.reshape(c,shp)
    a = np.reshape(a,shp)
    return np.linalg.norm(np.matmul(b,c)-a,2)

shp = (3,3)
x0 = []
x0.append(np.zeros(shp[0]*shp[1]))
x0.append(np.ones(shp[0]*shp[1]))
a = np.random.rand(shp[0],shp[1])
a = a.flatten()
res = scipy.optimize.minimize(fun, x0, args=(a,shp),callback=None)
#print (res)
print ((res['x'][0]))

x = np.reshape(res['x'][0],shp)
y = np.reshape(res['x'][1],shp)

# x = np.reshape(res,shp)
a = np.reshape(a,shp)
print (round((np.linalg.norm((np.matmul(x,y) - a),'fro'))*100/np.linalg.norm(a),20),"%")


TypeError: fun() missing 1 required positional argument: 'shp'