# reshape in function using scipy optimize 

In [ ]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize

# objective function to minimize:
# Sum (W - Sum a*s)

N = 64 #number of filters
M = 18

#filter sizes:

n = 5
m = 3

#generate random sequence of filters
W = []
for i in range(N):
    W.append(np.random.rand(n,m))


#definition of the objective function
def fun(params, W, n, m, N, M):

    #recovering the original structure of parameters
    A = params[:N*M].reshape((N,M))
    X = params[N*M:].reshape((M,n,m))

    #print("A.Shape: ", A.shape)
    #print("X.Shape: ", X.shape)
    
    res = 0
    for i in range(N):
        
        # calculating the linear combination of matrices
        a_X = 0
        for j in range(M):
            a_X += A[i,j]*X[j,:,:]
            #print("-"*5,j)
            
        # calculating sum of
        res += np.linalg.norm(W[i] - a_X, 2)
        
    return res


shape = (n,m)
params = []

#initializing coefficients for linear combination
params = np.random.rand(N*M+M*n*m)  # N*M for lc coefiicients and m*n*M for matrix weights

res = scipy.optimize.minimize(fun, params, args=(W,n,m,N,M), callback=None)

vals = res['x']

A = vals[:N*M].reshape((N,M))
X = vals[N*M:].reshape((M,n,m))

#print ("weights are:")
#print (A)

#print ("basis filters are:")
#print (W)

#random check
for i in range(N):
    coeff_i = A[i,:]
    A_sum = 0
    for j in range(M):
        A_sum += coeff_i[j]*X[j]
    print ("approximation of matrix", i)
    print (np.round((np.linalg.norm(W[i] - A_sum, 2))*100, 5), "%")

In [ ]:
X = params[1].reshape((M,n,m))
A = params[0].reshape((N,M))

print(A[0,:])
print(X[1,:,:])

In [10]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize


# objective function to minimize:
# Sum (W - Sum a*s)

N = 64 #number of filters
M = 15

#filter sizes:
n = 5
m = 5

#generate random sequence of filters

W = np.random.rand(N, n*m) 

# starting point
A = np.random.rand(N, M)
X = np.random.rand(M, n*m)

Max_Iter = 300
A_var = cvx.Variable(N, M)
X_var = cvx.Variable(M, n*m)


for i in range(Max_Iter):
    
    if i%5 == 0:
        print(i)
    
    objective_A = cvx.Minimize(cvx.norm(W - A_var*X,1))
    problem_A = cvx.Problem(objective_A, [])
    result_A = problem_A.solve() #solver = "SCS"
    
    if (np.linalg.norm(A - A_var.value,2) < 1e-7):
        print ("early termination A",i)
        break
    
    A = A_var.value
    
    objective_X = cvx.Minimize(cvx.norm(W - A*X_var,1))
    problem_X = cvx.Problem(objective_X, [])
    result_X  = problem_X.solve()
    
    if (np.linalg.norm(X - X_var.value,2) < 1e-7):
        print ("early termination X",i)
        break
    
    X = X_var.value
    
    
print((np.linalg.norm(W - np.matmul(A,X),2)/(np.linalg.norm(W,2)))*100,"%")

#recovering the original structure
W = np.reshape(W,(N,n,m))

A = A.view(type = np.ndarray)
X = X.view(type = np.ndarray)

A = np.reshape(A,(N,M))
X = np.reshape(X,(M,n,m))

#check
for i in range(N):
    A_sum = 0
    for j in range(M):
        A_sum += A[i,j]*X[j,:,:]
    print ("approximation of matrix", i)
    print (np.round((np.linalg.norm(W[i,:,:] - A_sum,1))*100, 2), "%")

0
5
10
15
20
early termination X 21
13.1404564886 %
approximation of matrix 0
99.81 %
approximation of matrix 1
47.01 %
approximation of matrix 2
32.29 %
approximation of matrix 3
140.47 %
approximation of matrix 4
49.03 %
approximation of matrix 5
155.2 %
approximation of matrix 6
79.79 %
approximation of matrix 7
71.03 %
approximation of matrix 8
124.86 %
approximation of matrix 9
81.31 %
approximation of matrix 10
124.17 %
approximation of matrix 11
97.91 %
approximation of matrix 12
87.15 %
approximation of matrix 13
110.57 %
approximation of matrix 14
127.96 %
approximation of matrix 15
82.89 %
approximation of matrix 16
113.36 %
approximation of matrix 17
65.5 %
approximation of matrix 18
97.99 %
approximation of matrix 19
27.97 %
approximation of matrix 20
93.19 %
approximation of matrix 21
54.7 %
approximation of matrix 22
81.57 %
approximation of matrix 23
106.38 %
approximation of matrix 24
33.0 %
approximation of matrix 25
80.99 %
approximation of matrix 26
117.81 %
approxim

In [12]:
print (np.matrix.round(X[2,:,:],3))

[[ 0.317  0.601  0.502  0.223  0.516]
 [ 0.412  0.139  0.001  0.24   0.584]
 [ 0.23   0.294  0.48   0.841  0.063]
 [ 0.072  0.267  0.673  0.692  0.074]
 [ 0.233  0.856  0.545  0.942  0.583]]


# vectorized implementation of basis decomposition with nuclear norm

In [254]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize

# returns low-basis representation of original weights W with shape N x n x m by
# linear combination of N matrices n x m with coefficients stored in matrix A
def find_basis(W, M, lmbd, Max_Iter, norm,tol):
    
    N = W.shape[0]
    n = W.shape[1]
    m = W.shape[2]
    
    # starting point
    W = W.reshape(N,n*m)
    
    A = np.random.rand(N, M)
    X = np.random.rand(M, n*m)

    A_var = cvx.Variable(N, M)
    X_var = cvx.Variable(M, n*m)


    for i in range(Max_Iter):

        if i%1 == 0:
            print(i)

        objective_A = cvx.Minimize(cvx.norm(W - A_var*X,norm))
        problem_A = cvx.Problem(objective_A, [])
        result_A = problem_A.solve() 

        if (np.linalg.norm(A - A_var.value,norm) < tol):
            print ("early termination A",i)
            break

        A = A_var.value

        #adding nuclear norm
        sum_nucl = 0
        slvr = None
        if lmbd != 0:
            slvr = "SCS"
            for j in range(M):
                x = X_var[j,:]
                x = cvx.reshape(x,n,m)
                sum_nucl += cvx.norm(x, 'nuc')

        objective_X = cvx.Minimize(cvx.norm(W - A*X_var,norm) + lmbd*sum_nucl)
        problem_X = cvx.Problem(objective_X, [])
        result_X  = problem_X.solve(solver = slvr)

        if (np.linalg.norm(X - X_var.value,norm) < tol):
            print ("early termination X",i)
            break

        X = X_var.value


    #print((np.linalg.norm(W - np.matmul(A,X),2)/(np.linalg.norm(W,2)))*100,"%")

    #recovering the original structure
    A = A.view(type = np.ndarray)
    X = X.view(type = np.ndarray)

    A = np.reshape(A,(N,M))
    X = np.reshape(X,(M,n,m))
    
    return A, X


# N = 64 #number of filters


# #filter size:
# n = 5
# m = 5

# #generate random sequence of filters

# W = np.random.rand(N,n,m) 
M = 14
#loading data
data = np.load('/home/pavel/Documents/Skoltech/NLA_Project/variables/scheme1_fr.npz')
shp = data['conv1/weights'].shape
new_weights = np.zeros((shp[0],shp[1],shp[2],M))
coeffs = np.zeros(shp[2],shp[3],M)
data = data['conv1/weights']
data = np.swapaxes(data, 0,3 )
data = np.swapaxes(data, 1,2 )
data = np.swapaxes(data, 1,3 )

#now channels axis is the last one
for c in range(data.shape[3]):
    print ("c = ",c)
    W = data[:,:,:,c]
    A, X = find_basis(W, M, lmbd = 0, Max_Iter = 100, norm = 1, tol = 1e-7)
    print ("done")
    #check
    for i in range(data.shape[0]):
        A_sum = 0
        for j in range(M):
            A_sum += A[i,j]*X[j,:,:]
        print ("approximation of matrix", i)
        print (np.round((np.linalg.norm(W[i,:,:] - A_sum,1))*100, 2), "%")
        print ("and some random?")
        print (np.round((np.linalg.norm(W[i,:,:] - np.random.rand(n,m)))*100, 2), "%")

(5, 5, 1, 32)
c =  0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
early termination A 54
done
approximation of matrix 0
38.34 %
and some random?
286.41 %
approximation of matrix 1
15.63 %
and some random?
308.31 %
approximation of matrix 2
8.45 %
and some random?
272.74 %
approximation of matrix 3
12.15 %
and some random?
275.56 %
approximation of matrix 4
18.92 %
and some random?
292.13 %
approximation of matrix 5
10.6 %
and some random?
318.19 %
approximation of matrix 6
19.41 %
and some random?
286.08 %
approximation of matrix 7
18.96 %
and some random?
293.1 %
approximation of matrix 8
29.79 %
and some random?
274.53 %
approximation of matrix 9
22.59 %
and some random?
337.55 %
approximation of matrix 10
10.6 %
and some random?
304.45 %
approximation of matrix 11
17.35 %
and some random?
240.9 %
approximation of matrix 12
19.75 %
and some random?
288.69 %
approximation of m

In [244]:
np.set_printoptions(suppress=True)
U,Sigma, V = np.linalg.svd(X[5,:,:])
print(np.matrix.round(Sigma,3))


32768
[ 3.307  0.905  0.738  0.518  0.139]


# decomposition using 1-rank matrices

In [231]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize


def find_1_rank_decomposition(W, N,K, n, m, Max_Iter, norm,tol):
    # starting point
    W = W.reshape(N,n*m)
    # initializing variable to optimize
    v_var = []
    h_var = []
    v = []
    h = []
    for k in range(K):
        v_var.append(cvx.Variable(n,N))
        h_var.append(cvx.Variable(N,m))

        # starting point 
        v.append(np.random.rand(n,N))
        h.append(np.random.rand(N,m))
    
    for i in range(Max_Iter):

        if i%10 == 0:
            print(i)
            
        fun_v = 0
        for j in range(N):
            for k in range(K):
            
                #temp1 = v_var[:,j]*np.array([h[j,:]])
                if np.array([h[k][j,:]]).shape == (1,m):
                    if k == 0:
                        temp1 = v_var[k][:,j]*np.array([h[k][j,:]])
                    else: 
                        temp1 += v_var[k][:,j]*np.array([h[k][j,:]])
                else:
                    if k == 0:
                        temp1 = v_var[k][:,j]*np.array(h[k][j,:])
                    else:
                        temp1 += v_var[k][:,j]*np.array(h[k][j,:])
                        
            temp1 = cvx.reshape(temp1,n*m,1)
            fun_v += cvx.norm(W[j,:] - temp1,norm)
        
        
        objective_v = cvx.Minimize(fun_v)
        problem_v = cvx.Problem(objective_v, [])
        result_v = problem_v.solve() #solver = "SCS"
        
        if (np.linalg.norm(v[0] - v_var[0].value,norm) < tol):
            print ("early termination v",i)
            break

        for k in range(K): 
            v[k] = v_var[k].value
            
        fun_h = 0

        for j in range(N):
            for k in range(K):
                if k == 0:
                    temp2 = np.array(v[k][:,j])*h_var[k][j,:]
                else:
                    temp2 += np.array(v[k][:,j])*h_var[k][j,:]
            temp2 = cvx.reshape(temp2,n*m,1)
            fun_h += cvx.norm(W[j,:] - temp2,norm)
               
        objective_h = cvx.Minimize(fun_h)
        problem_h = cvx.Problem(objective_h, [])
        result_h  = problem_h.solve() #solver = "SCS"
        if (np.linalg.norm(h[0] - h_var[0].value,norm) < tol):
            print ("early termination X",i)
            break

        for k in range(K): 
            h[k] = h_var[k].value
    #recovering the original structure
    for k in range(K):
        h[k] = h[k].view(type = np.ndarray)
        v[k] = v[k].view(type = np.ndarray)
    
    return h, v


N = 5 #number of filters

#filter size:
n = 5
m = 5

#generate random sequence of filters

W = np.random.rand(N,n,m) 
K = 2

H, V = find_1_rank_decomposition(W, N,K, n, m, Max_Iter = 300, norm = 1, tol = 1e-8)
#check
for i in range(N):

    res = 0
    for k in range(K):
        res += np.matmul(np.array([H[k][i,:]]).T,np.array([V[k][:,i]]))
        
    print ("approximation of matrix", i, ",",
          np.round((np.linalg.norm(W[i,:,:] - res,1))*100, 1), "%")
    print ("and comparison with random matrix?",i,",",
            np.round((np.linalg.norm(W[i,:,:] - np.random.rand(n,m)))*100, 1), "%")
    S,Z,D = np.linalg.svd(W[i,:,:])
    l = 1
    W_ = np.dot(S[:,:l], np.dot(np.diag(Z)[:l,:l], D[:l,:]))
    print ("SVD decomposition?",np.round(np.linalg.norm(W[i,:,:] - W_)*100, 1), "%")

0
early termination X 3
approximation of matrix 0 , 101.2 %
and comparison with random matrix? 0 , 232.6 %
SVD decomposition? 110.5 %
approximation of matrix 1 , 82.0 %
and comparison with random matrix? 1 , 194.6 %
SVD decomposition? 106.9 %
approximation of matrix 2 , 97.5 %
and comparison with random matrix? 2 , 234.7 %
SVD decomposition? 109.2 %
approximation of matrix 3 , 125.3 %
and comparison with random matrix? 3 , 214.0 %
SVD decomposition? 119.2 %
approximation of matrix 4 , 55.1 %
and comparison with random matrix? 4 , 199.1 %
SVD decomposition? 81.4 %


In [101]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize


# objective function to minimize:
# Sum (W - Sum a*s)

N = 15 #number of filters
M = 8

#filter sizes:
n = 3
m = 3

#generate random sequence of filters

W = np.random.rand(N, n, m) 

# starting point
A = np.random.rand(N,M)
X = np.random.rand(M,n,m)

S = []
for i in range(M):
    S.append(cvx.Variable(n,m))

# S = cvx.Variable(M,n,m)
A_var = cvx.Variable(N, M)

Max_Iter = 5


for i in range(Max_Iter):
    
    if i%5 == 0:
        print(i)
    
    fun_A = 0
    f_A = cvx.Variable(n,m)
    for p in range(N): 
        f_A += W[p,:,:]
        for k in range(M):
            f_A -= A_var[p,k]*X[k,:,:]
        fun_A += cvx.norm(f_A,1)

    objective_A = cvx.Minimize(fun_A)
    problem_A = cvx.Problem(objective_A, [])
    result_A = problem_A.solve(solver = "SCS") #solver = "SCS"
    if (np.linalg.norm(A - A_var.value,2) < 1e-7):
        print ("early termination A",i)
        break
    
    A = A_var.value
    
    fun_X = 0
    f_X = cvx.Variable(n,m)
    for p in range(N):
        f_X += W[p,:,:]  
        for k in range(M):
            f_X -= A[p,k]*S[k]
        fun_X += cvx.norm(f_X,1)
        #fun_X += 1.5*cvx.norm(S[k],'nuc')
    
    objective_X = cvx.Minimize(fun_X)
    problem_X = cvx.Problem(objective_X, [])
    result_X  = problem_X.solve(solver = "SCS")
    
    # here check for norm of X
    diff = 0
    for j in range(M):
        diff += np.linalg.norm(X[j,:,:] - S[j].value,2)
        
    if (diff < 1e-7):
        print ("early termination X",i)
        break
    
    for j in range(M):
        X[j,:,:] = S[j].value
    


#recovering the original structure

A = A.view(type = np.ndarray)
X = X.view(type = np.ndarray)

#check
for i in range(N):
    A_sum = 0
    for j in range(M):
        A_sum += A[i,j]*X[j,:,:]
    print ("approximation of matrix", i)
    print (np.round((np.linalg.norm(W[i,:,:] - A_sum,1))*100, 2), "%")

print(X[1,:,:])

0
approximation of matrix 0
86.45 %
approximation of matrix 1
0.03 %
approximation of matrix 2
26.98 %
approximation of matrix 3
26.99 %
approximation of matrix 4
0.75 %
approximation of matrix 5
0.11 %
approximation of matrix 6
0.03 %
approximation of matrix 7
16.57 %
approximation of matrix 8
19.2 %
approximation of matrix 9
29.21 %
approximation of matrix 10
29.32 %
approximation of matrix 11
15.73 %
approximation of matrix 12
15.87 %
approximation of matrix 13
0.37 %
approximation of matrix 14
0.38 %
[[ 0.5808218   0.99735639  0.50303305]
 [ 0.41543549  0.15780439  0.05742168]
 [ 0.80647582  0.42009534  0.53532226]]


In [102]:
U,Sigma, V = np.linalg.svd(X[3,:,:])
print(Sigma)

[ 1.84100492  0.59970226  0.20291488]


In [ ]:
import numpy as np
import cvxpy as cvx
import scipy
from scipy import optimize
from scipy.optimize import minimize

# returns low-basis representation of original weights W with shape N x n x m by
# linear combination of N matrices n x m with coefficients stored in matrix A
def find_basis(W, M, lmbd, Max_Iter, norm,tol):
    
    N = W.shape[0]
    n = W.shape[1]
    m = W.shape[2]
    
    # starting point
    W = W.reshape(N,n*m)
    
    A = np.random.rand(N, M)
    X = np.random.rand(M, n*m)

    A_var = cvx.Variable(N, M)
    X_var = cvx.Variable(M, n*m)


    for i in range(Max_Iter):

        if i%1 == 0:
            print(i)

        objective_A = cvx.Minimize(cvx.norm(W - A_var*X,norm))
        problem_A = cvx.Problem(objective_A, [])
        result_A = problem_A.solve() 

        if (np.linalg.norm(A - A_var.value,norm) < tol):
            print ("early termination A",i)
            break

        A = A_var.value

        #adding nuclear norm
        sum_nucl = 0
        slvr = None
        if lmbd != 0:
            slvr = "SCS"
            for j in range(M):
                x = X_var[j,:]
                x = cvx.reshape(x,n,m)
                sum_nucl += cvx.norm(x, 'nuc')

        objective_X = cvx.Minimize(cvx.norm(W - A*X_var,norm) + lmbd*sum_nucl)
        problem_X = cvx.Problem(objective_X, [])
        result_X  = problem_X.solve(solver = slvr)

        if (np.linalg.norm(X - X_var.value,norm) < tol):
            print ("early termination X",i)
            break

        X = X_var.value


    #print((np.linalg.norm(W - np.matmul(A,X),2)/(np.linalg.norm(W,2)))*100,"%")

    #recovering the original structure
    A = A.view(type = np.ndarray)
    X = X.view(type = np.ndarray)

    A = np.reshape(A,(N,M))
    X = np.reshape(X,(M,n,m))
    
    return A, X


# N = 64 #number of filters


# #filter size:
# n = 5
# m = 5

# #generate random sequence of filters

# W = np.random.rand(N,n,m) 
M = 14
#loading data
data = np.load('variables/scheme1_fr.npz')
shp = data['conv2/weights'].shape
# new_weights = np.zeros((shp[0],shp[1],shp[2],M))
# coeffs = np.zeros(shp[2],shp[3],M)
data = data['conv2/weights']
C = data.shape[2]
N = data.shape[3]
data = data.reshape(shp[0],shp[1],-1)
data = np.swapaxes(data, 0,2 )
data = np.swapaxes(data, 1,2 )
W = data
#now channels axis is the last one

A, X = find_basis(W, M, lmbd = 0, Max_Iter = 100, norm = 1, tol = 1e-7)


#check
print (data.shape[0])
for i in range(N):
    A_sum = 0
    for j in range(M):
        A_sum += A[i,j]*X[j,:,:]
    print ("approximation of matrix", i)
    print (np.round((np.linalg.norm(W[i,:,:] - A_sum,1))*100, 1), "%")
    
A = A.reshape(C,N,M)
# A - matrix of coefficients N*C by M, X
np.savez('variables/scheme1_fr_decomposition.npz', coeffs = A, basis = X )


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [265]:
G = np.array([range(27)]).reshape(3,3,3)
print(G)

print(G.reshape(3,-1))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
